/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.5-dev at Tue Mar  8 21:19:47 2016. */

#include "submarine.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ControlMessage_fields[3] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, ControlMessage, type, type, 0),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, ControlMessage, dive, type, &Dive_fields),
    PB_LAST_FIELD
};

const pb_field_t Dive_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, Dive, offset_s, offset_s, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, Dive, depth_m, offset_s, 0),
    PB_LAST_FIELD
};

const pb_field_t SubmarineMessage_fields[4] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, SubmarineMessage, type, type, 0),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, SubmarineMessage, status, type, &Status_fields),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, SubmarineMessage, data, status, &Datum_fields),
    PB_LAST_FIELD
};

const pb_field_t Status_fields[5] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, Status, type, type, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, Status, spent_time_s, type, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, CALLBACK, OTHER, Status, message, spent_time_s, 0),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, Status, informations, message, &Status_Informations_fields),
    PB_LAST_FIELD
};

const pb_field_t Status_Informations_fields[2] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, Status_Informations, battery_percentage, battery_percentage, 0),
    PB_LAST_FIELD
};

const pb_field_t Datum_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, Datum, timestamp, timestamp, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, Datum, depth, timestamp, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, Datum, temperature, depth, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, Datum, pressure, temperature, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ControlMessage, dive) < 65536 && pb_membersize(SubmarineMessage, status) < 65536 && pb_membersize(SubmarineMessage, data) < 65536 && pb_membersize(Status, informations) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_ControlMessage_Dive_SubmarineMessage_Status_Status_Informations_Datum)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ControlMessage, dive) < 256 && pb_membersize(SubmarineMessage, status) < 256 && pb_membersize(SubmarineMessage, data) < 256 && pb_membersize(Status, informations) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_ControlMessage_Dive_SubmarineMessage_Status_Status_Informations_Datum)
#endif


